app/resources/cy/translation/ethnicasian.json, app/resources/cy/translation/ethnicblack.json, app/resources/cy/translation/ethnicmixed.json, app/resources/cy/translation/ethnicother.json, app/resources/cy/translation/ethnicwhite.json, app/resources/cy/translation/gender.json, app/resources/en/translation/ethnicasian.json, app/resources/en/translation/ethnicblack.json, app/resources/en/translation/ethnicmixed.json, app/resources/en/translation/ethnicother.json, app/resources/en/translation/ethnicwhite.json, app/resources/en/translation/gender.json, app/steps/ui/gender/template.html
Changes made to align with the content matrix:
- Updated the question text.
- Added input field for option 'no' in gender question.
```
[ ] Yes
[x] No
```
=> Content update

charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/requirements.yaml
https://tools.hmcts.net/jira/browse/PCQ-109
Removed `idam-pr` references.
```
[ ] Yes
[ ] No
```
=> Remove idam-pr references

app/config.js, app/featureToggles.js, app/routes.js, app/views/includes/layout.html, test/accessibility/a11yTest.js, test/service-stubs/feature-toggles.js
N/A
Remove the Welsh feature toggle
```
[ ] Yes
[X] No
```
=> Remove Welsh feature toggle

app/steps/ui/endpage/index.js, app/steps/ui/startpage/index.js
N/A
Pass back language flag to invoking application
```
[ ] Yes
[X] No
```
=> Pass back language flag

app/core/runners/UIStepRunner.js, app/core/steps/Step.js, app/core/steps/ValidationStep.js, app/steps/ui/startpage/index.js, app/views/includes/layout.html, test/unit/testStartPage.js
N/A
Dynamic Back link instead of relying on JS's history.go(-1)
```
[ ] Yes
[X] No
```
=> Dynamic Back link

app/resources/cy/translation/common.json, app/resources/en/translation/common.json, app/steps/ui/startpage/template.html, app/views/includes/two_thirds_form.html, test/component/testStartPage.js
https://tools.hmcts.net/jira/browse/PCQ-116
- Set phase banner to Alpha.
Removed the 'Why we are asking these questions' section from the start page.
```
[ ] Yes
[x] No
```
=> PCQ-116: Set phase to Alpha. Removed 'Why we are asking...' section on start page

app.js
=> Use CSRF Token

test/unit/static/testAccessibility.js, test/unit/testDateOfBirth.js, test/unit/testEnglishLevel.js
https://tools.hmcts.net/jira/browse/PCQ-113
Add unit tests
```
[ ] Yes
[X] No
```
=> PCQ-113: Add unit tests

test/end-to-end/features/probate.feature, test/end-to-end/pages/startpage/startpage.js, test/end-to-end/step_definitions/probatepcqjourney.js, test/end-to-end/utils.js
https://tools.hmcts.net/jira/browse/PCQ-17
Add call to service endpoint for the start page end-to-end tests. This allows the invoking parameters to be set.
```
[ ] Yes
[x] No
```
=> PCQ-17 Add call to service endpoint

app/assets/javascripts/back-button.js, app/resources/cy/translation/endpage.json, app/resources/en/translation/endpage.json, app/steps/ui/endpage/template.html, app/views/includes/layout.html, test/accessibility/a11yTest.js
- Fix back button
- Add title to end page
```
[ ] Yes
[x] No
```
=> Dac points

app.js, app/resources/cy/translation/common.json, app/resources/en/translation/common.json, app/views/includes/layout.html, test/accessibility/a11yTest.js
https://tools.hmcts.net/jira/browse/PCQ-136
- Set title to question and add GOV.UK
```
[ ] Yes
[x] No
```
=> PCQ-136: DAC Readiness

test/component/testDateOfBirth.js, test/component/testDisability.js, test/component/testDisabilityImplications.js, test/component/testEthnicGroupAsian.js, test/component/testEthnicGroupBlack.js, test/component/testEthnicGroupMixed.js, test/component/testEthnicGroupOther.js, test/component/testEthnicGroupWhite.js, test/component/testGender.js, test/component/testLanguage.js, test/component/testMaritalStatus.js, test/component/testPregnant.js, test/component/testReligion.js, test/component/testSex.js, test/component/testSexualOrientation.js
https://tools.hmcts.net/jira/browse/PCQ-103
- Add components tests to cover all options for all pages.
```
[ ] Yes
[x] No
```
=> PCQ-103: Add tests for all options

charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/requirements.yaml
Update nodejs chart version to 1.10.0
```
[ ] Yes
[ ] No
```
=> Update nodejs chart version

app/components/auth.js, app/middleware/registerIncomingService.js, config/default.yaml
https://tools.hmcts.net/jira/browse/PCQ-172
JWT to expected format
```
[ ] Yes
[ ] No
```
=> PCQ-172: JWT to expected format

charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/requirements.yaml
Increase Redis version to 10.5.7
```
[ ] Yes
[ ] No
```
=> Increase Redis version to 10.5.7

app/steps/ui/dateofbirth/index.js, app/steps/ui/endpage/index.js, app/steps/ui/language/index.js, app/steps/ui/startpage/index.js, test/component/testEndPage.js, test/component/testStartPage.js, test/unit/testDateOfBirth.js, test/unit/testEndPage.js, test/unit/testLanguage.js, test/unit/testStartPage.js
https://tools.hmcts.net/jira/browse/PCQ-208
- Fix language level not resetting on option change
- Fix DOB fields not clearing when selecting 'prefer not to say'
- Remove locale from returnUrl
```
[ ] Yes
[ ] No
```
=> Minor Issue Fixes

app/core/steps/Step.js, app/journeys/cmc.js, app/journeys/sscs.js, app/resources/cy/translation/variable/cmc.json, app/resources/cy/translation/variable/divorce.json, app/resources/cy/translation/variable/probate.json, app/resources/cy/translation/variable/sscs.json, app/resources/en/translation/variable/README.md, app/resources/en/translation/variable/cmc.json, app/resources/en/translation/variable/divorce.json, app/resources/en/translation/variable/probate.json, app/resources/en/translation/variable/sscs.json, test/unit/testEndPage.js, test/unit/testShutterPage.js, test/unit/testStartPage.js
https://tools.hmcts.net/jira/browse/PCQ-56
Text on certain pages will change based on the invoking service
```
[ ] Yes
[ ] No
```
=> PCQ-56: Variable text functionality

app/components/string-utils.js, app/core/steps/Step.js, app/middleware/registerIncomingService.js, test/unit/middleware/testRegisterIncomingService.js, test/unit/testStringUtils.js
* Return URL will be prefixed with HTTPS if not already.
* Bug fix when actor does not exist in variable content.
```
[ ] Yes
[ ] No
```
=> PCQ-63: Prefix HTTPS on returnUrl && Bug fix

app/steps/ui/dateofbirth/index.js, test/component/testDateOfBirth.js, test/unit/testDateOfBirth.js
https://tools.hmcts.net/jira/browse/PCQ-188
Show error if year is greater than present year.
```
[ ] Yes
[ ] No
```
=> PCQ-188: Show error on invalid year

app/middleware/initSession.js, app/registerIncomingService.js
https://tools.hmcts.net/jira/browse/PCQ-247
Session gets reset when the service endpoint is called.
```
[ ] Yes
[ ] No
```
=> PCQ-247: Reset the session for new service

config/default.yaml
https://tools.hmcts.net/jira/browse/PCQ-246
Add the new PCQ survey link
```
[ ] Yes
[ ] No
```
=> PCQ-246: Correct survey link

test/end-to-end/codecept.conf.js, test/end-to-end/step_definitions/probatepcqjourney.js
=> Retry scenario when fail

app/resources/cy/translation/religion.json, app/resources/en/translation/religion.json, app/steps/ui/religion/template.html
https://tools.hmcts.net/jira/browse/PCQ-250
Changed the religion page text area to a text field.
```
[ ] Yes
[ ] No
```
=> PCQ-250: Text area to text field

app/resources/cy/translation/common.json, app/resources/en/translation/common.json
https://tools.hmcts.net/jira/browse/PCQ-249?src=confmacro
Change the expanding link text from:
Why we are asking these questions
to
Why are we asking this question
```
[ ] Yes
[ ] No
```
=> PCQ-249: Update 'Why are we asking this question' text

app/steps/ui/dateofbirth/template.html
https://tools.hmcts.net/jira/browse/PCQ-287
```
[ ] Yes
[x] No
```
=> PCQ-287: Preselect DoB radio button

app/assets/javascripts/mutually-exclusive-checkboxes.js
https://tools.hmcts.net/jira/browse/PCQ-260
```
[ ] Yes
[ ] No
```
=> PCQ-260: Fix 'None of the above' not deselecting other options on IE

charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.perftest.template.yaml, charts/pcq-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-288
Increase resources for all envs
```
[ ] Yes
[ ] No
```
=> PCQ-288: Increase resources for all envs

config/default.yaml
https://tools.hmcts.net/jira/browse/PCQ-274
Update SmartSurvey link
```
[ ] Yes
[ ] No
```
=> PCQ-274: Update smartsurvey link

app/core/runners/UIStepRunner.js, test/util/TestWrapper.js
https://tools.hmcts.net/jira/browse/PCQ-206
Use POST/REDIRECT/GET pattern when there is an error on the page.
```
[ ] Yes
[x] No
```
=> PCQ-206: Fix form resubmission

app/middleware/optOut.js, app/routes.js, app/steps/ui/startpage/template.html, test/component/testStartPage.js, test/unit/middleware/testOptOut.js
https://tools.hmcts.net/jira/browse/PCQ-159
Clicking the opt out button on the start page will now clear the pcq answers and then redirect to the return url.
```
[ ] Yes
[ ] No
```
=> PCQ-159: Opt Out functionality

app/registeredServices.json, app/resources/cy/translation/shutterpage.json, app/resources/en/translation/shutterpage.json, app/steps/ui/shutterpage/index.js, app/steps/ui/shutterpage/template.html, test/component/testShutterPage.js, test/unit/testShutterPage.js
https://tools.hmcts.net/jira/browse/PCQ-400
Rework shutter redirect links to allow multiple per service.
Adds Probate caveat link
```
[ ] Yes
[x] No
```
=> PCQ-400: Rework shutter redirect links to allow multiple per service

app/healthcheck.js, app/registerIncomingService.js, charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/requirements.yaml, package.json, test/unit/middleware/testRegisterIncomingService.js, test/unit/testHealthcheck.js, yarn.lock
=> Revert "PCQ-342: Add readiness check and upgrade node chart"

charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-273
Chart changes for PCQ-273 - PR #73: Add probate token key to secret list.
```
[ ] Yes
[x] No
```
=> PCQ-273: Chart changes

Jenkinsfile_CNP, test/end-to-end/pages/startpage/startpage.js
https://tools.hmcts.net/jira/browse/PCQ-273
Add token to e2e tests
```
[ ] Yes
[x] No
```
=> PCQ-273: Add token to e2e tests

test/end-to-end/smoke/smoketest.js
https://tools.hmcts.net/jira/browse/PCQ-273
Add token to smoke tests
```
[ ] Yes
[x] No
```
=> PCQ-273: Add token to smoke test

app/middleware/invoker.js, app/views/invoker/template.html
https://tools.hmcts.net/jira/browse/PCQ-273
Change invoker.js version to ensure server does not cache old version.
```
[ ] Yes
[ ] No
```
=> PCQ-273: Change invoker.js version

charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-417
Chart changes required for #99
```
[ ] Yes
[ ] No
```
=> PCQ-417: Chart changes for CMC

charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/requirements.yaml, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-342
Chart changes for #104
```
[ ] Yes
[x] No
```
=> PCQ-342: Chart changes

charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-391
Chart changes for PR #98
```
[ ] Yes
[x] No
```
=> PCQ-391: Chart changes

app/registeredServices.json, test/unit/utils/testInvoker.js
https://tools.hmcts.net/jira/browse/PCQ-592
Add CORESPONDENT actor type to divorce service.
```
[ ] Yes
[x] No
```
=> PCQ-592: Add CORESPONDENT actor to divorce

test/crossbrowser/supportedBrowsers.js
=> updated browser names and versions

Jenkinsfile_nightly, package.json
=> Pcq 625 nightly func

bin/run-functional-tests.sh, config/custom-environment-variables.yaml, config/testing.yaml, package.json, test/end-to-end/codecept.conf.js, test/end-to-end/helpers/TestConfigurator.js, test/end-to-end/smoke.conf.js, test/end-to-end/smoke/smoketest.js
https://tools.hmcts.net/jira/browse/PCQ-640
Functional and smoke tests now run against the correct URLs for PRs. 
```
[ ] Yes
[x] No
```
=> PCQ-640: Functional and Smoke tests correct URL

app/routes.js, app/shutter.js, config/default.yaml, config/testing.yaml, test/accessibility/a11yTest.js, test/component/testShutterPage.js, test/unit/utils/testFeatureToggle.js
https://tools.hmcts.net/jira/browse/PCQ-558
Remove 'Force offline' toggle.
```
[ ] Yes
[x] No
```
=> PCQ-558: Remove 'Force Offline' toggle

app/middleware/validateParams.js, config/default.yaml, test/accessibility/a11yTest.js, test/component/common/testCommonContent.js, test/component/testEndPage.js, test/unit/middleware/testValidateParams.js, test/util/TestWrapper.js
https://tools.hmcts.net/jira/browse/PCQ-557
Removed the 'Enforce parameters' toggle.
```
[ ] Yes
[x] No
```
=> PCQ-557: Remove 'Enforce Parameters' toggle

audit.json, package.json, yarn.lock
- Add false positives to fix security scan
- Update sonar scanner to remove deprecation warning
```
[ ] Yes
[x] No
```
=> Nightly fix

app/middleware/invoker.js, config/default.yaml, test/unit/middleware/testInvoker.js
https://tools.hmcts.net/jira/browse/PCQ-559
Remove 'Invoker' toggle
```
[ ] Yes
[x] No
```
=> PCQ-559: Remove 'Invoker' toggle

app/middleware/validateParams.js
https://tools.hmcts.net/jira/browse/PCQ-624
Always allow static pages to be accessed.
```
[ ] Yes
[x] No
```
=> PCQ-624: Allow static pages to be accessed without journey

app/resources/cy/translation/variable/divorce.json, app/resources/en/translation/variable/divorce.json
PCQ-656
Static text added for corespondent actor for Divorce.
```
[ ] Yes
[X ] No
```
=> PCQ656 - Updated the divorce text for corespondent

Jenkinsfile_nightly, audit.json
=> Security fix

audit.json
=> added false positives

audit.json
=> false positive added

audit.json
https://tools.hmcts.net/jira/browse/PCQ-341
Add false positives to audit.json to fix security scan in nightly build. All fingerprints verified by secops as false positives.
```
[ ] Yes
[x] No
```
=> Add false positives to audit.json

bin/run-functional-tests.sh, bin/run-smoke-tests.sh, test/config.js, test/end-to-end/helpers/TestConfigurator.js
https://tools.hmcts.net/jira/browse/PCQ-716
Remove proxy usage from functional tests
```
[ ] Yes
[x] No
```
=> PCQ-716: Remove proxy usage from functional tests

app/components/error.js, app/core/initSteps.js, app/core/steps/Step.js, app/utils/FormatUrl.js
https://tools.hmcts.net/jira/browse/PCQ-692
Fixes Sonar code smells.
```
[ ] Yes
[x] No
```
=> PCQ-692: Fix Sonar code smells

app/core/steps/Step.js, app/middleware/optOut.js, app/routes.js, config/default.yaml, test/unit/middleware/testOptOut.js, test/unit/testStartPage.js
https://tools.hmcts.net/jira/browse/PCQ-705
- Prevent sending opt out multiple times
- Remove the opt out feature flag
```
[ ] Yes
[x] No
```
=> PCQ-705: Prevent sending opt-out multiple times

package.json, test/component/testDateOfBirth.js, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-746
Fix issue with year used in component test and update some libraries causing minor vulnerabilities.
```
[ ] Yes
[x] No
```
=> PCQ-746: Minor update to fix year in test.

config/testing.yaml, package.json, test/end-to-end/codecept.conf.js, test/end-to-end/helpers/JSWait.js, test/end-to-end/step_definitions/probatepcqjourney.js, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-752
Improve stability of FE tests.
```
[ ] Yes
[x] No
```
=> PCQ-752 Updated timeout settings to make FE e2e tests more stable.

package.json, test/end-to-end/helpers/JSWait.js, test/end-to-end/pages/steps.js, test/end-to-end/saucelabs.conf.js, test/end-to-end/step_definitions/probatepcqjourney.js
https://tools.hmcts.net/jira/browse/PCQ-780
Improve stability of e2e tests run nightly.
```
[ ] Yes
[x] No
```
=> PCQ-780-FixFrontendNightlyTests

audit.json
https://tools.hmcts.net/jira/browse/PCQ-780
Adding false positive to FE audit.json file.
```
[ ] Yes
[x] No
```
=> PCQ-780 Adding false positive to frontend audit,json file.

test/end-to-end/helpers/JSWait.js, test/end-to-end/step_definitions/probatepcqjourney.js
https://tools.hmcts.net/jira/browse/PCQ-780
Ok now we know tests are stable just upping the reties so this doesn't need to bother us ever again!
```
[ ] Yes
[x] No
```
=> PCQ-780: Minor update to retries.

charts/pcq-frontend/Chart.yaml
https://tools.hmcts.net/jira/browse/PCQ-727
Update to charts helm library to show pipeline change is working.
```
[ ] Yes
[ ] No
```
=> PCQ-729 Updated charts version to show pipeline update worked.

audit.json
https://tools.hmcts.net/jira/browse/PCQ-1234
Testing pipeline following AKS deploy failure to AAT.
```
[ ] Yes
[x] No
```
=> PCQ-1234 Test build pipeline.

app/components/encryption-token.js, test/unit/components/testVerifyToken.js, test/unit/middleware/testInvoker.js
https://tools.hmcts.net/jira/browse/PCQ-722
Updated encryption for PCQ token generation. Falls back to lagacy encryption of new encryption fails.
```
[ ] Yes
[x] No
```
=> PCQ-722 update token encryption.

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-831
Fix to correct issues raised in PCQ-831 this time with mutation tests failing.
```
[ ] Yes
[x] No
```
=> PCQ-831: Another fix to mutation tests

Dockerfile, app.js
https://tools.hmcts.net/jira/browse/PCQ-839
Resolve a couple of fortify frontend issues
```
[ ] Yes
[x] No
```
=> PCQ-839: Set docker user and enforce secure protocol

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-849
Fix to Regular Expression Denial of Service, Command Injection and Path Traversal issues.
```
[ ] Yes
[x] No
```
=> PCQ-849: Update to fix vulnerabilities.

audit.json
https://tools.hmcts.net/jira/browse/PCQ-852
Adding a false positive for a hidden infrastructure file not in the repo found during owasp zaproxy run.
```
[ ] Yes
[x] No
```
=> PCQ-852: Resolve new security vulnerability

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-867 sub task https://tools.hmcts.net/jira/browse/PCQ-868
Fix new vulnerability in trim-newlines
```
[ ] Yes
[x] No
```
=> PCQ-867 PI22 Sprint 3 Tech Debt Fix new vulnerability in trim-newlines

audit.json
https://tools.hmcts.net/jira/browse/PCQ-890
Fix to add false positive.
```
[ ] Yes
[x] No
```
=> PCQ-890: Fix frontend vulnerability

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1023
Addressed PCQ frontend Vulnerability
```
[ ] Yes
[ x] No
```
=> PCQ-1023 Changed dependency path-parse and url-parse

app/journeys/new_divorce_law.js, app/registeredServices.json, app/resources/cy/translation/variable/new_divorce_law.json, app/resources/en/translation/variable/new_divorce_law.json, config/custom-environment-variables.yaml, config/default.yaml, test/unit/utils/testInvoker.js
https://tools.hmcts.net/jira/browse/PCQ-917
Initial frontend integration for No-fault divorce. 
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[x] No
```
=> PCQ-917 Initial No-Fault Divorce frontend integration

app/setupSecrets.js, charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-917
Add the NFD secrets to setup and chart values
```
[ ] Yes
[x] No
```
=> PCQ-917: Add the NFD secrets to setup and chart values

Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/PCQ-988
This change is about Syncing other branches with master for pcq-frontend.
```
[ ] Yes
[x] No
```
=> Pcq frontend synce branches with master

app/middleware/optOut.js, charts/pcq-frontend/values.preview.template.yaml, package.json, test/end-to-end/helpers/TestConfigurator.js, test/unit/middleware/testOptOut.js, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-984
This change in PCQ-Frontend is about even though there is no pcqAnswer and user has clicked on "I Don't want to answer these questions" backend is called and a true flag is set in optOut column in database while other values will be null. Test cases has also been modified to fulflill this functionality.
```
[ ] Yes
[x] No
```
=> PCQ-984 Set Optout Flag Frontend

test/crossbrowser/supportedBrowsers.js, test/end-to-end/saucelabs.conf.js
https://tools.hmcts.net/jira/browse/PCQ-1092
This change will increase the delay from 2000 to 4000 and enable extend debugging and capture performance on sauce lab while doing x-browser test.
```
[ ] Yes
[x] No
```
=> PCQ-1092 X Broswer Investigation

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1133
Update to fix 2 vulnerablilities.
```
[ ] Yes
[x] No
```
=> Pcq 1133 fix vulnerability

app/healthcheck.js
https://tools.hmcts.net/jira/browse/PCQ-1089
This change is to remove readiness check to see if 500 errors come down
```
[ ] Yes
[x] No
```
=> PCQ-1089 Removing Rediness check

app/healthcheck.js
https://tools.hmcts.net/jira/browse/PCQ-1089
This is to remove heath redness check so that 500 errors can be reduced
```
[ ] Yes
[x] No
```
=> PCQ-1089 500 errors

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1140
This change is to fix dependency check related to json-schema
```
[ ] Yes
[x] No
```
=> PCQ-1140 dependency check

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1144
This change is to upgrade properties-volume to 0.0.13
```
[ ] Yes
[x] No
```
=> PCQ-1144 Properties-volume Upgarde

package.json
- [x ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/PCQ-1142
Including the journey tests in code coverage
```
[ ] Yes
[x] No
```
=> including journeys in code coverage

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PCQ-1190
This change is disable Fortify Scan
```
[ ] Yes
[x] No
```
=> Pcq 1190 frontend disable fortify

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PCQ-1212
This change to enable fortify scan
```
[ ] Yes
[x] No
```
=> PCQ-1212 Enable fortify Scan

app/middleware/registerIncomingService.js
https://tools.hmcts.net/jira/browse/PCQ-846
This change is about , if service send partyId with + character , it still call PCQ questions successfully.
At the moment if partyId has + characters in PCQ it's coming as space. 
So changing space to '+' character in partyId.
```
[ ] Yes
[x] No
```
=> PCQ-846 implement for + fix

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1240
This change to Fix dependency check for node-fetch libraries
```
[ ] Yes
[x] No
```
=> PCQ-1240 Dependency check fixed

app/resources/en/translation/static/accessibility.json
https://tools.hmcts.net/jira/browse/PCQ-1239
This change was about Accessibility Statement date update
```
[ ] Yes
[x] No
```
=> PCQ-1239 Accessiblity Statement update

app/components/encryption-token.js
https://tools.hmcts.net/jira/browse/PCQ-1237
This change it to spit Authlog in logs for lower environment.
```
[ ] Yes
[x] No
```
=> PCQ-1237 Auth Tag in log

app/setupSecrets.js, charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.yaml, config/custom-environment-variables.yaml, config/default.yaml
https://tools.hmcts.net/jira/browse/PCQ-1242
This is to move user key to vault.
```
[ ] Yes
[x] No
```
=> PCQ-1242 moving LD_USER_KEY to vault

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1236
This ticket is about updating latest HMCTS libraries
```
[ ] Yes
[x] No
```
=> PCQ-1236 Updating HMCTS Library to latest vesrion

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1290
This change is to fix dependency check for node-sagas
```
[ ] Yes
[x] No
```
=> PCQ-1290 Dependency check

charts/pcq-frontend/Chart.yaml
https://tools.hmcts.net/jira/browse/PCQ-1339
This change is to upgrade chart node js
```
[ ] Yes
[x] No
```
=> Chart Nodejs upgrade

security.sh
=> Update security.sh for debugging

bin/githooks/pre-commit, bin/preinstall.sh, package.json
Adds pre commit hook to bump the app version on new PRs. 
```
[ ] Yes
[x] No
```
=> Add pre-commit hook to bump patch version

app/core/steps/Step.js, app/utils/AsyncFetch.js, app/utils/FeatureToggle.js, app/utils/FormatUrl.js, test/unit/middleware/testOptOut.js, test/unit/middleware/testSanatizeRequestBody.js, test/unit/services/testService.js, test/unit/utils/testAsyncFetch.js
https://tools.hmcts.net/jira/browse/PCQ-1109
Fix Sonar issues
```
[ ] Yes
[x] No
```
=> PCQ-1109 Fix Sonar issues

audit.json
https://tools.hmcts.net/jira/browse/PCQ-817
This change is to fix security scan on Frontend
```
[ ] Yes
[x] No
```
=> PCQ-817 Security scan fix

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-960
This change is to fix dependency check I'm Frontend
```
[ ] Yes
[x] No
```
=> PCQ-960 Dependency check fix

app.js, app/core/runners/UIStepRunner.js, app/routes.js, app/views/includes/layout.html, app/views/includes/scripts.html, config/default.yaml, package.json
https://tools.hmcts.net/jira/browse/PCQ-1292
- Add session id hidden element.
- Add the app version as a JS const.
This will allow us to understand which sessions are coming from which service as well as the app version in Dynatrace RUM.
```
[ ] Yes
[x] No
```
=> PCQ-1292 Add Session Parameters for Dynatrace

app/views/includes/layout.html, app/views/includes/scripts.html, package.json
https://tools.hmcts.net/jira/browse/PCQ-1292
Move app version from JS variable into HTML el. 
```
[ ] Yes
[x] No
```
=> PCQ-1292 Move app version into HTML el

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1451
Update to async module version.
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> PCQ-1451: Dependency fixes

audit.json
https://tools.hmcts.net/jira/browse/PCQ-1422
Added fingerprint to audit.json to suppress OWASP Zaproxy alerts.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> PCQ-1422-pcq-frontend-security-scan-40024_SQL-Injection

app/assets/javascripts/cookie-v1.js, app/steps/ui/static/cookies/template.html, package.json
https://tools.hmcts.net/jira/browse/PCQ-970
The cookie preferences from requires a class name change, that has been fixed in this pr. I've also passed the true parameter to the enableSessionReplay function, this is required to allow for session replays.
```
[ ] Yes
[x] No
```
=> PCQ-970 Fix cookie form V1 changes

app/resources/cy/translation/static/accessibility.json, app/resources/en/translation/static/accessibility.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1370
This is to change heading from Equality and Diversity Helplines to Helplines
```
[ ] Yes
[x] No
```
=> PCQ-1370 Accessibilty change

app/assets/javascripts/dtrum-optout.js, package.json
https://tools.hmcts.net/jira/browse/PCQ-971
Set cookie status to ensure cookie pref can be read.
```
[ ] Yes
[x] No
```
=> PCQ-971 Set cookie status to determine cookie pref

app/steps/ui/startpage/index.js, app/steps/ui/startpage/template.html, package.json
https://tools.hmcts.net/jira/browse/PCQ-971
Add timestamp for dtrum optout js file to prevent caching issue
```
[ ] Yes
[x] No
```
=> PCQ-971 Add timestamp for dtrum optout js file

app/journeys/online_plea.js, app/registeredServices.json, app/resources/cy/translation/shutterpage.json, app/resources/cy/translation/static/accessibility.json, app/resources/cy/translation/variable/online_plea.json, app/resources/en/translation/shutterpage.json, app/resources/en/translation/static/accessibility.json, app/resources/en/translation/variable/online_plea.json, app/setupSecrets.js, app/steps/ui/static/accessibility/template.html, charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.yaml, config/custom-environment-variables.yaml, config/default.yaml, package.json, test/component/testShutterPage.js, test/unit/core/testServiceData.json, test/unit/services/testServiceInvokerData.json, test/unit/testShutterPage.js, test/unit/utils/testInvoker.js
https://tools.hmcts.net/jira/browse/PCQ-1262
This change is to setup SJS (Crime) integration with PCQ
```
[ ] Yes
[x] No
```
=> PCQ-1262 Setup SJS service

app.js, package.json
https://tools.hmcts.net/jira/browse/PCQ-912
Exclude RUM Beacon POST calls from CSRF checks
```
[ ] Yes
[x] No
```
=> PCQ-912 Exclude RUM Beacon POST calls from CSRF checks

app.js, package.json
https://tools.hmcts.net/jira/browse/PCQ-912
Exclude RUM Beacon POST calls from CSRF checks - Enabling in prod
```
[ ] Yes
[x] No
```
=> PCQ-912 Exclude RUM beacon calls from CSRF checks - Prod

package.json, renovate/configure/renovate.json
https://tools.hmcts.net/jira/browse/PCQ-1335
This change is to configure renovate for frontend
```
[ ] Yes
[x] No
```
=> PCQ-1335 Configuring renovate for frontend

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-914
This change is to fix security scan build failure
```
[ ] Yes
[x] No
```
=> PCQ-914 Security Scan fix

app/assets/javascripts/dtrum-optout.js, package.json
Cookie status null check
```
[ ] Yes
[x] No
```
=> PCQ-971 Cookie status null check

package.json
https://tools.hmcts.net/jira/browse/PCQ-940
This change is to fix dependency check
```
[ ] Yes
[x] No
```
=> PCQ-940 dependency check

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-938
This Change is to fix security scan. 
```
[ ] Yes
[x] No
```
=> PCQ-Frontend Security scan fix

.github/renovate.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-896
This change is to configure renovate
```
[ ] Yes
[x] No
```
=> PCQ-896 configuring renovate

charts/pcq-frontend/Chart.yaml, package.json
https://tools.hmcts.net/jira/browse/PCQ-1457
Upgrade nodejs chart version to 2.4.5
```
[ ] Yes
[x] No
```
=> Upgrade nodejs chart version

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1463
This change is to fix security scan
```
[ ] Yes
[x] No
```
=> PCQ-1463 Security Scan fix

app/resources/cy/translation/static/accessibility.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1522
This change is for IAC accessibilty number in welsh.
```
[ ] Yes
[x] No
```
=> PCQ-1522 Accessibility for IAC

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1475
Update healthcheck module to latest version
```
[ ] Yes
[x] No
```
=> PCQ-1475 Update healthcheck module

Jenkinsfile_nightly, package.json
https://tools.hmcts.net/jira/browse/PCQ-1536
This change is to disable nightly build during weekend
```
[ ] Yes
[x] No
```
=> PCQ-1536 Disable nightly build during weekend

app/resources/cy/translation/static/terms.json, app/resources/en/translation/static/terms.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1532
Update terms & conditions - service management
```
[ ] Yes
[x] No
```
=> PCQ-1532 Update terms & conditions - service management

app/registeredServices.json, package.json, test/unit/testShutterPage.js
https://tools.hmcts.net/jira/browse/PCQ-84
This change is to redirect ET link to production before we have aat
```
[ ] Yes
[x] No
```
=> PCQ-84 changing ET redirect link to production

.dockerignore, .gitignore, Dockerfile, app/healthcheck.js, createVersionFile.js, package.json, test/mutation/stryker.conf.js, test/route/app/healthcheck.int.js, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1547
Update version file contents to YAML format. Updated file name to remove extension as per HMCTS healthcheck requirements.
```
[ ] Yes
[x] No
```
=> PCQ-1547 Update version file

app/journeys/adoption.js, package.json
https://tools.hmcts.net/jira/browse/PCQ-1594
Remove 'Pregnancy' question from Adoption journey
```
[ ] Yes
[x] No
```
=> PCQ-1594 Remove 'Pregnancy' question from Adoption journey

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile_CNP, package.json
https://tools.hmcts.net/jira/browse/PCQ-1595
Cleanup helm release on success
```
[ ] Yes
[x] No
```
=> PCQ-1595 Cleanup helm release on success

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1626
This change is to fix dependency check related to jsonwebtoken
```
[ ] Yes
[x] No
```
=> PCQ-1626 dependency fix

Jenkinsfile_CNP, Jenkinsfile_nightly, package.json
https://tools.hmcts.net/jira/browse/PCQ-1639
Changing after to afterAlways
```
[ ] Yes
[x] No
```
=> PCQ-1639 Changing after to afterAlways

config/custom-environment-variables.yaml, package.json
https://tools.hmcts.net/jira/browse/PCQ-1563
Config change
```
[ ] Yes
[x] No
```
=> PCQ-1563 Juror Digital config change

app/setupSecrets.js, charts/pcq-frontend/values.yaml, config/custom-environment-variables.yaml, package.json
https://tools.hmcts.net/jira/browse/PCQ-1563
Changing secret name
```
[ ] Yes
[x] No
```
=> PCQ-1563 changing token key name

.github/dependabot.yml, package.json
https://tools.hmcts.net/jira/browse/PCQ-1648
This change is to configure dependabot in pcq-frontend for Thursday 6pm.
```
[ ] Yes
[x] No
```
=> PCQ-1648 configuring dependabot on particular day

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1714
This change is to ignore urls
```
[ ] Yes
[x] No
```
=> PCQ-1714 ignore urls

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1714
```
[ ] Yes
[x] No
```
=> PCQ-1714 ignoring urls

app/registeredServices.json, package.json, test/unit/services/testServiceInvokerData.json, test/unit/utils/testInvoker.js
https://tools.hmcts.net/jira/browse/PCQ-1507
Remove actor "Subject" for special Tribunal
```
[ ] Yes
[x] No
```
=> PCQ-1506 Remove actor subject

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1735
This change is to suppress url on pcq-frontend
```
[ ] Yes
[x] No
```
=> PCQ-1735 Security scan fix

app/registeredServices.json, package.json, test/unit/testShutterPage.js
https://tools.hmcts.net/jira/browse/PCQ-1646
Change redirect link to production url
```
[ ] Yes
[x] No
```
=> PCQ-1646 change redirect link to production url

app.js, package.json
https://tools.hmcts.net/jira/browse/PCQ-1784
This change is to add Dynatrace.com
```
[ ] Yes
[x] No
```
=> PCQ-1784 adding dynatrace

package.json, test/java/build.gradle, test/java/gradle/wrapper/gradle-wrapper.properties
https://tools.hmcts.net/jira/browse/PCQ-1786
Update fortify scan gradle library
```
[ ] Yes
[x] No
```
=> PCQ-1786-fix-fortify-scan

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1788
This is to fix security scan
```
[ ] Yes
[x] No
```
=> PCQ-1788 Security scan fix

README.md, package.json
https://tools.hmcts.net/jira/browse/PCQ-1785
Empty PR to restart application
```
[ ] Yes
[x] No
```
=> PCQ-1785 empty PR to start application

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1792
Fix security Scan
```
[ ] Yes
[x] No
```
=> PCQ-1792 Security scan fix

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1812
Suppressing URLs
```
[ ] Yes
[x] No
```
=> PCQ-1812 suppression

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1812
zaproxy suppression
```
[ ] Yes
[x] No
```
=> PCQ-1812 more suppression

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1812
More suppression for zaproxy
```
[ ] Yes
[x] No
```
=> PCQ-1812 security scan fix

audit.json
https://tools.hmcts.net/jira/browse/PCQ-1841
added 1 fingerprint into audit.json file
=> PCQ-1841 - added 1 fingerprint into audit.json file

app/views/includes/scripts.html, package.json
https://tools.hmcts.net/jira/browse/PCQ-1846
This change is to improve Dynatrace monitoring in pcq
```
[ ] Yes
[x] No
```
=> PCQ-1846 adding scripts for dynatrace monitoring

audit.json
Security scan fix
```
[ ] Yes
[x] No
```
=> Update audit.json for security scan fix

.pnp.cjs, package.json, yarn.lock
revert upgrade of govuk-frontend library
```
[ ] Yes
[x] No
```
=> Revert Back govuk-frontend upgrade from 5.0.0 to 4.7.0

audit.json, charts/pcq-frontend/Chart.yaml, package.json
https://tools.hmcts.net/jira/browse/PCQ-1850
added fingerprint
=> PCQ-1850 - added one further fingerprint into audit.json file

audit.json
Security scan fix
```
[ ] Yes
[x] No
```
=> Update audit.json to fix security scan

app/views/includes/scripts.html, package.json
Adding Real user monitoring for aat
```
[ ] Yes
[x] No
```
=> PCQ-1853 adding real user monitoring for aat

config/aat.yaml, package.json
This change to add aat file to pick aat environment
```
[ ] Yes
[x] No
```
=> PCQ-1853 adding aat file to pick aat environment

app/views/includes/scripts.html, charts/pcq-frontend/Chart.yaml, config/aat.yaml, package.json
This change is to use testing environment instead of aat
```
[ ] Yes
[x] No
```
=> PCQ-1835 changing to testing env

app/views/includes/scripts.html, charts/pcq-frontend/values.aat.template.yaml, charts/pcq-frontend/values.preview.template.yaml, package.json
To find what env it is
```
[ ] Yes
[x] No
```
=> PCQ-1853 finding env

app/views/includes/scripts.html, charts/pcq-frontend/values.aat.template.yaml, package.json
reverting the change as it's not working
```
[ ] Yes
[x] No
```
=> PCQ-1853 revert chages

charts/pcq-frontend/Chart.yaml, config/aat.yaml, package.json
Adding env into aat.yaml
```
[ ] Yes
[x] No
```
=> PCQ-1853 adding environment

charts/pcq-frontend/Chart.yaml
Bump chart version
```
[ ] Yes
[x] No
```
=> Bump chart version

app/views/includes/scripts.html, package.json
Add script for non production env
```
[ ] Yes
[x] No
```
=> PCQ-1853 change script for non production env

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1864
Fix security scan for 22-01-2024 failures
```
[ ] Yes
[x] No
```
=> PCQ-1864 fix securityscan 22-01-2024

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1864
Fix scrutiny scan
```
[ ] Yes
[x] No
```
=> PCQ-1864 fixing more securing scan

audit.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1864
Fix security scan
```
[ ] Yes
[x] No
```
=> PCQ-1864 security scan fix

.pnp.cjs, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1874
Downgrading playwright to 1.37.1
```
[ ] Yes
[x] No
```
=> PCQ-1874 downgrading playwright to 1.37.1 as previous

.pnp.cjs, package.json, yarn.lock
Bump ip version from 1.1.8 to 1.1.9
```
[ ] Yes
[x] No
```
=> BUmping Ip version

.pnp.cjs, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1811
jsonwebtoken upgrade
```
[ ] Yes
[x] No
```
=> PCQ-1811 jsonwebtoken upgrade

Jenkinsfile_CNP, app/views/includes/tag_manager.html, package.json
Install playwright before smoke test
```
[ ] Yes
[x] No
```
=> install paywright before smoke test

.pnp.cjs, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1817
nodemon upgrade
```
[ ] Yes
[x] No
```
=> PCQ-1817 nodemon upgrade

app/core/steps/ValidationStep.js, package.json
https://tools.hmcts.net/jira/browse/PCQ-1817
Remove date-time from  addFormat 
```
[ ] Yes
[x] No
```
=> PCQ-1817 remove date-time from add format

.pnp.cjs, app/components/error.js, app/core/steps/ValidationStep.js, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1817
Revert acv upgrade as mutation test and PR failing 
```
[ ] Yes
[x] No
```
=> PCQ-1817 revert ajv upgrade

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1740
CodeceptJS upgrade
```
[ ] Yes
[x] No
```
=> PCQ-1740 codecptjs upgrade

.pnp.cjs, package.json, yarn.lock
Bump puppeteer
```
[ ] Yes
[x] No
```
=> Bump puppeteer

app/resources/en/translation/static/accessibility.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-1858
This change is to update accessibility statement
```
[ ] Yes
[x] No
```
=> PCQ-1858 update accessibility statement

charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.yaml, package.json
https://tools.hmcts.net/jira/browse/PCQ-1878
Enable  spotInstances 
```
[ ] Yes
[x] No
```
=> PCQ-1878 enable pcq-frontend for spotInstaces in lower evironment

charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.yaml, package.json
https://tools.hmcts.net/jira/browse/PCQ-1880
Enable Autoscaling
```
[ ] Yes
[x] No
```
=> PCQ-1880 autoscaling

audit.json, package.json
Ignore another zaproxy warning
=> ignore zaproxy raised issue

audit.json
Added 1 fingerprint into audit.json file
https://tools.hmcts.net/jira/browse/PCQ-1898
=> PCQ-1898 - added 1 fingerprint into audit.json file

app.js, package.json
https://tools.hmcts.net/jira/browse/PCQ-1900
Disable accept-ranges header
=> PCQ-1900 remove accept-ranges header

.pnp.cjs, app.js, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1900
Enable gzip compression which is incompatible with accept-ranges header in a hope that accept-ranges not going to appear
=> PCQ-1900 enable gzip compression

.gitignore, app/resources/cy/translation/variable/prl_ca.json, app/resources/cy/translation/variable/prl_da.json, app/resources/en/translation/variable/prl_ca.json, app/resources/en/translation/variable/prl_da.json, package.json, test/unit/core/testServiceData.json
Add missing start page paragraph for prl.
Add missing start page paragraph for prl.
```
[ ] Yes
[x] No
```
=> Add missing start page paragraph for prl.

Jenkinsfile_nightly, package.json
https://tools.hmcts.net/jira/browse/LAU-841
=> LAU-841 enable security scan once a month only

app/views/includes/scripts.html, package.json
Injecting manually dynatrace script
=> PCQ-1900 inject dynatrace script manually

Jenkinsfile_nightly, package.json
https://tools.hmcts.net/jira/browse/PCQ-1899
import and use yarnbuilder instead of using sh to run yarn install. 
```
[ ] Yes
[ ] No
```
=> use yarn builder to install playwright

.pnp.cjs, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1852
Upgrade gov uk
```
[ ] Yes
[x] No
```
=> PCQ-1852 gov uk library upgrade

.pnp.cjs, app/views/includes/layout.html, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1852
revert back to 4.8.0
```
[ ] Yes
[x] No
```
=> PCQ-1852 revert back govuk-frontend 4.8.0

app.js, app/components/app-insights.js, package.json
https://tools.hmcts.net/jira/browse/PCQ-1758
Missing function call
```
[ ] Yes
[x] No
```
=> PCQ-1758 missing function call

app/resources/cy/translation/variable/prl_ca.json, app/resources/en/translation/variable/prl_ca.json, package.json, test/unit/core/testServiceData.json
https://tools.hmcts.net/jira/browse/PCQ-1906
Remove extra line from start page
```
[ ] Yes
[x] No
```
=> PCQ-1906 start page text

.pnp.cjs, .pnp.loader.mjs, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1907
Reverting back  commit "93a4fe649fadb75a119f93cf199383078fbff76f"
```
[ ] Yes
[x] No
```
=> PCQ-1907 revert back mocha

app/components/app-insights.js, app/middleware/optOut.js, app/middleware/returnToService.js, app/middleware/validateUrl.js, app/routes.js, app/steps/ui/endpage/template.html, eslint.config.mjs, package.json, test/component/testEndPage.js, test/unit/middleware/testReturnToService.js
https://tools.hmcts.net/jira/browse/PCQ-1760
Adding new get path return-to service
```
[ ] Yes
[x] No
```
=> pcq-1760 adding return to service path

app/middleware/startPageBackService.js, package.json
https://tools.hmcts.net/jira/browse/PCQ-1961
page back service will now return 200 response instead of 0 response that is being flagged by azure logs
```
[ ] Yes
[ ] No
```
=> back to service to return a 200 json response

.pnp.cjs, app/components/app-insights.js, app/setupSecrets.js, charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.yaml, config/custom-environment-variables.yaml, config/default.yaml, package.json, yarn.lock
update application insights to version 3 from v2. dont merge yet
```
[ ] Yes
[ ] No
```
=> update app insights to version 3

.pnp.cjs, package.json, test/mutation/stryker.conf.js, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1914
upgrade mocha to newest version upgrades stryker mutations and mocha runner to newer versions.
Updated stryker config to ignore json files as there seems to be a bug between stryker and yarn pnp 
```
[ ] Yes
[ ] No
```
=> upgraded mocha and stryker mutations

app/middleware/continueToQuestions.js, app/routes.js, package.json
https://tools.hmcts.net/jira/browse/PCQ-1969
Adding tracer on continue to question button when coming from start-page
```
[ ] Yes
[x] No
```
=> PCQ-1969 adding tracer on continue to question button

.pnp.cjs, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-1967
Upgrade codecept library to 3.6.6
```
[ ] Yes
[x] No
```
=> PCQ-1967 upgrade to codecept library

charts/pcq-frontend/Chart.yaml, package.json
=> Update chart to create a new image.

charts/pcq-frontend/Chart.yaml
revert redis helm release version
```
[ ] Yes
[x] No
```
=> Revert redis helm release version to 20.3.0

.pnp.cjs, package.json, yarn.lock
https://tools.hmcts.net/jira/browse/PCQ-2010
Revert back codecept to 3.6.10
```
[ ] Yes
[x] No
```
=> PCQ-2010 revert codecept to 3.6.10

.github/renovate.json, .pnp.cjs, package.json, yarn.lock
Revert codeceptjs to 3.6.10
```
[ ] Yes
[x] No
```
=> revert codecept

charts/pcq-frontend/Chart.yaml
Update nods chart version
```
[ ] Yes
[x] No
```
=> Update nodes chart version to oci version

app/resources/en/translation/startpage.json, charts/pcq-frontend/Chart.yaml, charts/pcq-frontend/values.preview.template.yaml, package.json
https://tools.hmcts.net/jira/browse/PCQ-2017
```
[ ] Yes
[ ] No
```
=> Add focus to privacy policy link

app.js, app/views/includes/layout.html, package.json
https://tools.hmcts.net/jira/browse/PCQ-2015
Set correct language in html tag
```
[ ] Yes
[x] No
```
=> PCQ-2015 set correct language in html tag

app/resources/en/translation/common.json, package.json
https://tools.hmcts.net/jira/browse/PCQ-2018
Feedback link hidden text is confusing
```
[ ] Yes
[ ] No
```
=> Remove aria label

app/resources/cy/translation/static/accessibility.json, app/resources/en/translation/static/accessibility.json, config/default.yaml, package.json
https://tools.hmcts.net/jira/browse/PCQ-2023
```
[ ] Yes
[x] No
```
=> PCQ-2023 Update accessibility statement.

package.json, test/java/build.gradle
https://tools.hmcts.net/jira/browse/CME-518
Replace jitpack with azure artifactory
```
[ ] Yes
[x] No
```
=> CME-518 replace jitpack with azure

.pnp.cjs, package.json, yarn.lock
Revert codecept to 3.6.10
```
[ ] Yes
[x] No
```
=> Revert codecept to 3.6.10
